### ISSUE TITLE
你好，如果<build>中设置了<finalName>，打包会报错

### ISSUE THREAD

**Issue by blinkfox** [JoyLau/joylau-springboot-daemon-windows#4]
你好，如果<build>中设置了`<finalName>`，打包会报错，因为打包机制里面你是读了版本号的，而如果单独设置了finalName的话，Maven 打包就没有版本号了吧。

```xml
<build>
        <finalName>demo-server</finalName>
</build>
```

**Comment by JoyLau** [comment]
是的,插件会去读取前一个打包程序生成的 jar , 默认的名称是 artifactId + version, 如果定义了 finalName,且名称和 artifactId  不一致的话,会导致打包之后的 jar 名称改变,那么这个插件会找不到生成的 jar 包

**Comment by blinkfox** [comment]
嗯，这个问题倒不要紧，看你是否修复呗

**Comment by blinkfox** [comment]
还有一个建议就是几个 `bat` 文件可以统一放到 `bin` 目录下是不是好点儿呢

**Comment by JoyLau** [comment]
多谢建议😊
