### ISSUE TITLE
日志如何拆分

### ISSUE THREAD

**Issue by william-abel** [JoyLau/joylau-springboot-daemon-windows#9]
你好 我SpringBoot 用到了这个  我用log4j2 做日志 但是运行后 日志还是被输出到了 logs/*.err.log  logs/*.out.log  logs/*.wrapper.log  请问 如何设置 ?

**Comment by JoyLau** [comment]
logs 下日志的输出取决于程序在控制台的输出
你可能需要在 application.yml 指定日志的输出位置:
logging:
  file: /path/xxxxxx

william-abel <notifications@github.com> 于2020年8月18日周二 上午5:23写道：
